#!/usr/bin/env python3
import argparse
import re
from pathlib import Path


XY_RE = re.compile(r"\(xy\s+([-0-9.]+)\s+([-0-9.]+)\)")
LAYER_RE = re.compile(r'\(layer\s+"[FB]\.(Cu|Mask)"\)')


def extract_blocks(text, token):
    blocks = []
    index = 0

    while True:
        start = text.find(token, index)
        if start == -1:
            return blocks

        depth = 0
        end = start
        while end < len(text):
            char = text[end]
            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
                if depth == 0:
                    end += 1
                    break
            end += 1

        blocks.append(text[start:end])
        index = end


def format_number(value):
    return f"{value:.6f}".rstrip("0").rstrip(".")


def convert_poly(block, side, origin_x, origin_y, scale, mirror):
    def replace_point(match):
        local_x = float(match.group(1)) * scale
        local_y = float(match.group(2)) * scale
        board_x = origin_x + (-local_x if mirror else local_x)
        board_y = origin_y + local_y
        return f"(xy {format_number(board_x)} {format_number(board_y)})"

    block = block.replace("(fp_poly", "(gr_poly", 1)
    block = LAYER_RE.sub(lambda match: f'(layer "{side}.{match.group(1)}")', block)
    return XY_RE.sub(replace_point, block)


def convert_file(path, side, origin_x, origin_y, scale, mirror):
    text = path.read_text()
    blocks = extract_blocks(text, "(fp_poly")
    if not blocks:
        raise ValueError(f"No fp_poly blocks found in {path}")

    return [
        convert_poly(block, side, origin_x, origin_y, scale, mirror)
        for block in blocks
    ]


def write_ergogen_footprint(path, blocks, sources):
    source_lines = "\n".join(f"//   - {source}" for source in sources)
    body = "\n".join(blocks)
    path.write_text(
        f"""// Generated by novum/art/update_ergogen_artwork.py.
// Source KiCad artwork modules:
{source_lines}
// Do not edit this file directly; edit the .kicad_mod sources and regenerate.

module.exports = {{
  params: {{
    class: "RAW",
  }},
  body: () => String.raw`
{body}
  `,
}};
"""
    )


def main():
    parser = argparse.ArgumentParser(
        description="Convert KiCad bitmap footprints into the raw Ergogen artwork footprint."
    )
    parser.add_argument("--top", default="novum/art/top.kicad_mod", type=Path)
    parser.add_argument("--bottom", default="novum/art/bottom.kicad_mod", type=Path)
    parser.add_argument(
        "--output",
        default="novum/ergogen/footprints/artwork.js",
        type=Path,
    )
    parser.add_argument("--origin-x", default=117.02, type=float)
    parser.add_argument("--origin-y", default=88.24, type=float)
    parser.add_argument("--top-shift-x", default=-1.0, type=float)
    parser.add_argument("--top-shift-y", default=-2.0, type=float)
    parser.add_argument("--bottom-shift-x", default=0.0, type=float)
    parser.add_argument("--bottom-shift-y", default=0.0, type=float)
    parser.add_argument("--scale", default=1.0, type=float)
    parser.add_argument(
        "--mirror-bottom",
        action="store_true",
        help="Mirror bottom artwork horizontally around the artwork origin.",
    )
    args = parser.parse_args()

    top_blocks = convert_file(
        args.top,
        side="F",
        origin_x=args.origin_x + args.top_shift_x,
        origin_y=args.origin_y + args.top_shift_y,
        scale=args.scale,
        mirror=False,
    )
    bottom_blocks = convert_file(
        args.bottom,
        side="B",
        origin_x=args.origin_x + args.bottom_shift_x,
        origin_y=args.origin_y + args.bottom_shift_y,
        scale=args.scale,
        mirror=args.mirror_bottom,
    )

    write_ergogen_footprint(
        args.output,
        top_blocks + bottom_blocks,
        [args.top, args.bottom],
    )
    print(
        f"Wrote {args.output}: "
        f"{len(top_blocks)} front polygons, {len(bottom_blocks)} back polygons"
    )


if __name__ == "__main__":
    main()
