name: generate
on:
  pull_request:
  workflow_dispatch:

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-22.04
    permissions:
      issues: write
      pull-requests: write
      checks: write
      contents: read
      actions: read
    container:
      image: ghcr.io/henkru/ergo-builder:1.3.0
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Generate Version String
        id: vars
        run: |
          set -e
          HASH=$(git rev-parse --short HEAD)
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "version=${BRANCH}-${HASH}" >> $GITHUB_OUTPUT

      - name: Build Novum
        id: build
        uses: ./.github/actions/build
        with:
          version: ${{ steps.vars.outputs.version }}
        env:
          SKIP_BOTTOM_WITH_ART: ${{ !contains(github.event.head_commit.message, '[plot-bottom-art]') }}

      - name: Add Artifact Url
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Here is your ⌨️: ${{steps.build.outputs.artifact-url}}'
            })

      - name: Upload PCBs images
        if: github.event_name == 'pull_request'
        uses: edunad/actions-image@eef0041f6e888b797e3d11c3eee4791c01e08780
        with:
            path: ./out/novum/images/*.png
            title: '🧩 PCBs'
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload layout images
        if: github.event_name == 'pull_request'
        uses: edunad/actions-image@eef0041f6e888b797e3d11c3eee4791c01e08780
        with:
            path: ./out/novum/layout/*.svg
            title: '🧩 Keymaps'
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
