name: generate
on:
  pull_request:
  workflow_dispatch:

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-22.04
    permissions:
      issues: write
      pull-requests: write
      contents: read
    container:
      image: ghcr.io/henkru/ergo-builder:1.2.0
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Version String
        id: vars
        run: |
          set -e
          HASH=$(git rev-parse --short HEAD)
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "version=${BRANCH}-${HASH}" >> $GITHUB_OUTPUT

      - name: Build Novum
        id: build
        uses: ./.github/actions/build
        with:
          version: ${{ steps.vars.outputs.version }}

      - name: Add Artifact Url
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Here is your ⌨️: ${{steps.build.outputs.artifact-url}}'
            })
