name: generate
on:
  pull_request:
  workflow_dispatch:

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-22.04
    permissions:
      issues: write
      pull-requests: write
      checks: write
      contents: read
      actions: read
    container:
      image: ghcr.io/henkru/ergo-builder:1.3.2
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Generate Version String
        id: vars
        run: |
          set -e
          HASH=$(git rev-parse --short HEAD)
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "version=${BRANCH}-${HASH}" >> $GITHUB_OUTPUT

      - name: Build Novum
        id: build
        uses: ./.github/actions/build
        with:
          version: ${{ steps.vars.outputs.version }}
        # env:
        #   SKIP_BOTTOM_WITH_ART: ${{ !contains(github.event.head_commit.message, '[plot-bottom-art]') }}

      - name: Add Artifact Url
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Here is your ⌨️: ${{steps.build.outputs.artifact-url}}'
            })

      - name: Prepare PCB preview images
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          set -e
          mkdir -p out/novum/preview-images
          cp out/novum/images/left-*.png out/novum/preview-images/
          cp out/novum/images/right-*.png out/novum/preview-images/
          cp out/novum/images/switch_plate-*.png out/novum/preview-images/
          cp out/novum/images/bottom_board_empty-*.png out/novum/preview-images/
          cp out/novum/images/bottom_board_with_tenting_puck-*.png out/novum/preview-images/
          cp out/novum/images/bottom_board_with_art-*.png out/novum/preview-images/ 2>/dev/null || true

      - name: Upload PCB images
        if: github.event_name == 'pull_request'
        uses: Henkru/actions-image@b9c6f801c0164289ab059309b06b8d0bcdb13b88
        with:
          title: "🧩 PCBs"
          path: ./out/novum/preview-images/*.png
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload keymap images
        if: github.event_name == 'pull_request'
        uses: Henkru/actions-image@b9c6f801c0164289ab059309b06b8d0bcdb13b88
        with:
          title: "🧩 Keymaps"
          path: ./out/novum/layout/*.svg
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
