name: release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Release
    if: "!contains(github.event.head_commit.message, '[release]') && !contains(github.event.head_commit.message, '[nobuild]')"
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/henkru/ergo-builder:1.2.0
    permissions:
      contents: write
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Bump Version
        id: bump_version
        run: |
          if ${{ contains(github.event.head_commit.message, '[major]') }}; then
            VERSION=$(npm version major --git-tag-version false)
          elif ${{ contains(github.event.head_commit.message, '[patch]') }}; then
            VERSION=$(npm version patch --git-tag-version false)
          else
            VERSION=$(npm version minor --git-tag-version false)
          fi
          echo "Updated version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build Novum
        uses: ./.github/actions/build
        with:
          version: ${{ steps.bump_version.outputs.version }}

      - name: Update doc images
        run: |
          mkdir -p docs
          cp -r out/novum/images docs

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: '["package.json", "package-lock.json", "docs/images"]'
          default_author: github_actions
          message: "[release] ${{ steps.bump_version.outputs.version }}"
          tag: ${{ steps.bump_version.outputs.version }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            novum.zip
          tag_name: ${{ steps.bump_version.outputs.version }}
