name: release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build release
    if: "!contains(github.event.head_commit.message, '[release]') && !contains(github.event.head_commit.message, '[norelease]')"
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/henkru/ergo-builder:1.3.2
    permissions:
      contents: write
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Bump Version
        id: bump_version
        run: |
          if ${{ contains(github.event.head_commit.message, '[major]') }}; then
            VERSION=$(npm version major --git-tag-version false)
          elif ${{ contains(github.event.head_commit.message, '[patch]') }}; then
            VERSION=$(npm version patch --git-tag-version false)
          else
            VERSION=$(npm version minor --git-tag-version false)
          fi
          echo "Updated version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build Novum
        uses: ./.github/actions/build
        with:
          version: ${{ steps.bump_version.outputs.version }}

      - name: Update docs
        run: |
          mkdir -p docs
          cp -r out/novum/images docs
          cp -r out/novum/layout docs

      - name: Commit
        uses: Henkru/ghcommit-action@commit-output
        id: commit
        with:
          commit_message: "📦 ${{ steps.bump_version.outputs.version }} [release]"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
          file_pattern: 'package.json package-lock.json docs/images/*'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.bump_version.outputs.version }}',
              sha: '${{ steps.commit.outputs.commit-hash }}'
            })

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          commitMode: true
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "pr_template": "- #{{TITLE}}",
              "categories": [
                {
                    "title": "## Feature",
                    "labels": ["feat", "feature"]
                },
                {
                    "title": "## Fix",
                    "labels": ["fix", "bug"]
                }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "target": "$1"
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.build_changelog.outputs.changelog}}
          files: |
            novum.zip
          tag_name: ${{ steps.bump_version.outputs.version }}
